add test timer
anastasiialosytska/test-guru pull request #18
Opened 2022-04-11 14:13 UTC by anastasiialosytska

2022-04-11 15:58 UTC, BubuntuClu requested changes

2022-04-11 15:58 UTC, BubuntuClu commented on app/javascript/packs/utilities/test_timer.js
> +        setTimeout(function() { window.location.replace(location.origin + '/test_passages/' + control.dataset.id + '/result') }, 3000)
нажми лучше кнопку сабмита, чтобы отработала логика экшена `update`

2022-04-11 15:58 UTC, BubuntuClu commented on app/javascript/packs/utilities/test_timer.js
> +    var saved_countdown = localStorage.getItem('saved_countdown')
зачем тут использовать локалсторадж?

2022-04-11 16:30 UTC, anastasiialosytska commented on app/javascript/packs/utilities/test_timer.js
> +        setTimeout(function() { window.location.replace(location.origin + '/test_passages/' + control.dataset.id + '/result') }, 3000)
так экшен update перекинет нас на следующий вопрос, не факт же что время истечет, когда мы будем на последнем вопросе, а тут нас в любом случае перекидывает на результат

2022-04-11 16:31 UTC, anastasiialosytska commented on app/javascript/packs/utilities/test_timer.js
> +    var saved_countdown = localStorage.getItem('saved_countdown')
записывать туда после перехода на следующий вопрос оставшееся время

2022-04-13 16:30 UTC, BubuntuClu commented on app/javascript/packs/utilities/test_timer.js
> +        setTimeout(function() { window.location.replace(location.origin + '/test_passages/' + control.dataset.id + '/result') }, 3000)
в этом и суть, надо на бэке проверку добавить. чтобы не перекидывало дальше, а отрабатывала логика при переходе на страницу результата, письмо отправить, ченить еще сделать

2022-04-13 16:33 UTC, BubuntuClu commented on app/javascript/packs/utilities/test_timer.js
> +    var saved_countdown = localStorage.getItem('saved_countdown')
а зачем это делать? у тебя каждый раз рендерится вьюха, когда переходишь к новому вопросу. на вьюхе размести гденибудь код, который будет хранить в себе оставшееся время и из дата атрибута сможешь получить это время. выглядит как вариант гораздо проще чем твой и не надо задумываться об очищении стораджа

2022-04-14 17:33 UTC, BubuntuClu commented on app/javascript/packs/utilities/test_timer.js
> +        setTimeout(function() { window.location.replace(location.origin + '/test_passages/' + control.dataset.id + '/result') }, 3000)
редирект не переделала на сабмит

2022-04-14 17:33 UTC, BubuntuClu commented on app/views/test_passages/result.html.erb
> +<script type="text/javascript">
это получается уже не надо

2022-04-14 17:33 UTC, BubuntuClu commented on app/views/tests/index.html.erb
> +<script type="text/javascript">
и это тоже

2022-04-15 09:11 UTC, merged